set -g @catppuccin_window_status_style "rounded"

set -g @catppuccin_window_number "#I"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_number "#I"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_session_text "#S"
set -g @catppuccin_date_time_text "%Y-%m-%d %T"

# Add indicators to inactive windows
set -g @catppuccin_window_text " #W#{?window_activity_flag, 󰅅,}#{?window_bell_flag, 󰂚,}"
# Add indicators to the current window too (optional)
set -g @catppuccin_window_current_text " #W#{?window_activity_flag, 󰅅,}#{?window_bell_flag, 󰂚,}"
